### ISSUE TITLE
[Bug] 别名文章展示错误

### ISSUE THREAD

**Issue by liuran001** [openRin/Rin#158]
**Bug 描述**
我设置了一篇文章的别名为 about，同时设置了另一篇文章的别名为 test
当我访问 `/test` 时，显示的是文章 about
而 test 文章只能通过正常文章的 feed 目录进入
同时访问任意不存在的页面均会回到 about
已尝试清空缓存，问题仍然存在
在官方站点中也可复现 https://xeu.life/test

**Comment by OXeu** [comment]
找到原因了
https://github.com/OXeu/Rin/blob/main/server%2Fsrc%2Fservices%2Ffeed.ts#L162-L162
别名访问时 parseInt 获取的 id 是 undefined，导致所有别名的缓存键都是 `feed_` 😰

最近引入缓存搞坏了好多东西

**Comment by liuran001** [comment]
@OXeu 似乎还是有问题
比如我新建一篇文章，别名为 test
当我修改这篇文章时，它只会清除 `/feed/x` 的缓存，访问别名看到的仍是修改前的内容，需要手动清空缓存
然后 RSS 似乎也不会更新缓存，清空缓存对其无效

**Comment by OXeu** [comment]
* alias 缓存的问题已修复
* RSS 依赖于 crontab 工作，默认是 20 分钟更新一次，不是即时更新的

**Comment by liuran001** [comment]
> * alias 缓存的问题已修复
> * RSS 依赖于 crontab 工作，默认是 20 分钟更新一次，不是即时更新的

刚刚去看了一下 Workers 的记录，全都是错误
这会更新才有鬼了（
![image](https://github.com/OXeu/Rin/assets/32791471/8078eb40-4a09-4dfa-9466-c7c5c109d5c5)
这玩意有什么办法调试吗，看了一下好像没有显示错误日志的地方

**Comment by OXeu** [comment]
还是缓存引入导致的错误，晚点修一下
