### ISSUE TITLE
[Help] 博客部署好后，国内无法访问文章

### ISSUE THREAD

**Issue by igweek** [openRin/Rin#180]
按照部署步骤成功部署
但是中国国内访问无法获取文章列表，我这种情况正常吗？还是说没有正确部署？
![49](https://github.com/OXeu/Rin/assets/170249791/91f9ac1a-0482-4ecf-acb9-fc69023ddd93)

**Comment by OXeu** [comment]
确认是否在其他网络环境下能否正常访问，若可以则为成功部署，但需要为后端绑定自定义域名
https://github.com/OXeu/Rin/issues/166#issuecomment-2199435927

同时 F12 检查网络请求响应是否正常，若出现 500 及以上错误码说明未部署成功，具体错误搜索过往 issue
