### ISSUE TITLE
[Help] 问题描述github登录显示404: No such page!

### ISSUE THREAD

**Issue by 84348658** [openRin/Rin#205]
跟着教程一步步走的啊，显示404: No such page!
怎么回事啊

**Comment by OXeu** [comment]
Github OAuth 回调地址域名为后端域名：即 rin1.alist31.eu.org
另外由于我测试占用了第一个用户，还需要在 Cloudflare 中 D1 数据中删除 users 数据表中的数据
![图片](https://github.com/OXeu/Rin/assets/36541432/f04ccd6d-806f-487e-96b3-b70b6afa8c04)
![图片](https://github.com/OXeu/Rin/assets/36541432/9f6320af-0b98-4805-bb7d-cf4900297ef7)
