### ISSUE TITLE
[Bug] 更新代码到 2aebc6c 节点后，除了新加的 tag 接口，其他都报跨域请求的错误

### ISSUE THREAD

**Issue by IAn2018cs** [openRin/Rin#207]
<img width="247" alt="image" src="https://github.com/openRin/Rin/assets/18318073/399edede-9ae4-44d4-b4b9-a239e638e2b1">

<img width="561" alt="image" src="https://github.com/openRin/Rin/assets/18318073/9c44d12c-7d8d-4a58-8613-fcc9f221147c">

**Comment by OXeu** [comment]
简单排查了下不像是代码变更导致的问题，更像是某个依赖项或者 Cloudflare 的变更导致的，目前还没有找到原因

**Comment by OXeu** [comment]
应该是某些依赖版本更新导致的，现在加入了依赖版本锁定暂时修复了这个问题，具体有问题的依赖版本后续排查
