### ISSUE TITLE
[Feature Request] 希望页面底部可添加备案号

### ISSUE THREAD

**Issue by Hakureirm** [openRin/Rin#209]
比如[萌国ICP备案](https://icp.gov.moe/)

**Comment by OXeu** [comment]
已支持添加自定义 footer 内容，支持任意 HTML，示例值如下：
```html
<a class="text-sm text-neutral-500 font-normal hover:underline" href="https://icp.gov.moe/?keyword=20249944" target="_blank">萌ICP备20249944号</a>
```
效果
![图片](https://github.com/openRin/Rin/assets/36541432/30f5b22b-e7e6-4da8-a515-178d9fae94cf)
