### ISSUE TITLE
[Help] 我可以通过github登录，登录成功也能跳转回来，但是右上角不显示登录成功的头像

### ISSUE THREAD

**Issue by 534002646** [openRin/Rin#210]
我看了下d1数据库里也有我的用户数据，请问如何解决

**Comment by 534002646** [comment]
博客地址 https://blog.dogegg.online/

**Comment by 534002646** [comment]
![Uploading 20240710-173011.jpg…]()

**Comment by 534002646** [comment]
![20240710-173011](https://github.com/openRin/Rin/assets/32089821/cebd960b-e24e-42dd-be4e-9d64b832dd4a)

**Comment by Hakureirm** [comment]
我上午开始部署的，按流程走完，也遇到这种情况，死活登录不上去。然后刚才在自己分支sync了作者在下午最新的merge进来的内容，前后端都自动更新。现在就能正常登录了

**Comment by Hakureirm** [comment]
我看了一下你的repo里最新的commit是两天前的内容，大概Sync一下就好了

**Comment by SliverKeigo** [comment]
![image](https://github.com/openRin/Rin/assets/112426853/fa390d95-3860-47fd-addf-bfe98abb6eb4)
用戶信息是通過profile接口獲取數據的
![image](https://github.com/openRin/Rin/assets/112426853/eca32144-eec8-46b8-8375-f9532caa1c85)
但是你的接口存在跨域的情況

**Comment by OXeu** [comment]
参见 #203

自昨天晚上起就由于某些依赖版本更新破坏了 CORS 导致在此之后的部署都会出现跨域错误，最新的 main 分支已经加入了版本锁定来临时解决该问题，同步一下仓库就能解决

**Comment by 534002646** [comment]
> 参见#207
> 
> 自昨天起由于某些依赖版本更新破坏了 CORS 导致在此过程中的部署都会出现跨域错误，最新的主版本已经访问过版本控制来临时解决该问题，实时更新仓库就能解决

谢谢，我试一下

**Comment by 534002646** [comment]
> 参见 #207
> 
> 自昨天晚上起就由于某些依赖版本更新破坏了 CORS 导致在此之后的部署都会出现跨域错误，最新的 main 分支已经加入了版本锁定来临时解决该问题，同步一下仓库就能解决

能登陆了，解决了
