### ISSUE TITLE
[Bug] 光标位置不对

### ISSUE THREAD

**Issue by sergioperezcheco** [openRin/Rin#223]
**Bug 描述**

光标位置相较于文本位置发生偏移

**复现步骤**

1. 点开写作
2. 输入一行文字，或者全选一行文字
3. 随着输入光标会向前偏移
4. 刷新网页后无此问题

**期望行为**

期待修复问题，虽然刷新后会修复但会造成割裂感

**截图**

刷新前全选
![45132e4b1986ce4ab2214.png](https://img.checo.cc/file/45132e4b1986ce4ab2214.png)
刷新后全选
![f14fef651fb46df61f6b6.png](https://img.checo.cc/file/f14fef651fb46df61f6b6.png)

**环境变量**

完全按照文档

**Comment by CookieFJ** [comment]
有相同问题

**Comment by OXeu** [comment]
按理说全选后输入文字会删除选中的内容的
暂时没有成功复现

**Comment by sergioperezcheco** [comment]
> 暂时没有成功复现，有录屏可以参考一下吗？ 按理说全选后输入文字会删除选中的内容的

https://img.checo.cc/file/6337d7762c15d129e4e1b.mp4
我录了个屏

**Comment by sergioperezcheco** [comment]
> 暂时没有成功复现，有录屏可以参考一下吗？ 按理说全选后输入文字会删除选中的内容的

全选后再输入文字是会删除选中内容，我的意思是随着输入光标会向前偏移

**Comment by RTAkland** [comment]
确实有光标会向左偏移，但是只会出现在英文输入的情况下中文输入的话光标位置正常

**Comment by RTAkland** [comment]
https://github.com/user-attachments/assets/493a4bcd-d6ff-45ae-9a94-b3b1a381727b

**Comment by OXeu** [comment]
验证了一下在 Chrome 上确实有这个问题，Firefox 是 OK 的
