### ISSUE TITLE
[Feature Request] 偶然发现obsidian的同步插件可以使用r2桶,那么是否可以直接调用r2桶来发布本地写好的笔记呢

### ISSUE THREAD

**Issue by maxweiwei** [openRin/Rin#224]
**您的功能请求是否与问题相关？请描述**

因为本地笔记的很多内容不适合发布在博客上,但是现在在同步的过程中已经把图片内容同步到r2了,于是想着能否利用这一点更方便地发布笔记到blog上 [...]

**描述您想要的解决方案**

**描述你考虑过的替代方案**

**其他信息**

**Comment by OXeu** [comment]
手动复制粘贴也许是最快的
不过也许可以写一个插件来完成这个工作，但是短期内没有这个计划

**Comment by maxweiwei** [comment]
来信已收到。
