### ISSUE TITLE
上传图片失败

### ISSUE THREAD

**Issue by TIANXUAN13** [openRin/Rin#225]
**描述你遇到的问题**
写自己的内容的时候图片上传失败
**复现步骤**
1. xxxxx
2. xxx

**期望行为**

**截图**
<img width="758" alt="image" src="https://github.com/user-attachments/assets/999ef701-7102-40ab-8dd4-2e08025bf647">

**额外信息**

**Comment by OXeu** [comment]
F12 打开控制台可以看看上传返回的错误消息

**Comment by TIANXUAN13** [comment]
![image](https://github.com/user-attachments/assets/0d762415-4bee-417f-8bd8-e696ba915c38)
错误显示400是看这个吗

**Comment by TIANXUAN13** [comment]
响应头
![QQ_1721532836830](https://github.com/user-attachments/assets/cba8d10f-0531-4a52-8dbc-b1d8e9211a7f)
请求头
![QQ_1721532869337](https://github.com/user-attachments/assets/669b29cd-50d8-4ada-ac12-07badf4fef10)

**Comment by OXeu** [comment]
需要看的是响应体，响应头和请求头不需要，另外请求头的鉴权被截出来了，后面记得删一下截图 & 修改一下后端的 JWT_SECRET

**Comment by TIANXUAN13** [comment]
![Uploading image.png…]()
这个是响应体吗，我看翻译后显示的存储桶不存在这是怎么回事呢，麻烦啦

**Comment by TIANXUAN13** [comment]
![QQ_1721566041636](https://github.com/user-attachments/assets/226479fd-da6f-457c-9edd-d5bb351ce8ac)
重新发一下图片

**Comment by TIANXUAN13** [comment]
![QQ_1721566226635](https://github.com/user-attachments/assets/aca475ea-243a-4481-bc46-bddc9d561fe3)
这个是GitHub设置的环境变量
R2的存储桶我也是开了的 这个是不是用D1的存储就可以了还是要用到R2存储

**Comment by OXeu** [comment]
D1是存数据的，R2是存图片的，请检查一下 Cloudflare 面板中 R2 的名称是否是 image，是否可能是 images 写成了 image 之类的拼写错误

**Comment by TIANXUAN13** [comment]
OK，我查看了确实写错了，我修改后再部署一下

**Comment by TIANXUAN13** [comment]
佬，我修改了之后然后加载不出来文章了，点击登陆后显示这个样子
![QQ_1721570981385](https://github.com/user-attachments/assets/f7a83376-e9fc-4c91-a6ba-f9e4a41cf1b8)

**Comment by OXeu** [comment]
> 佬，我修改了之后然后加载不出来文章了，点击登陆后显示这个样子
> ![QQ_1721570981385](https://github.com/user-attachments/assets/f7a83376-e9fc-4c91-a6ba-f9e4a41cf1b8)
> 

同步最新仓库

**Comment by TIANXUAN13** [comment]
怎么同步呢佬，这个还没用过同步

**Comment by OXeu** [comment]
> 怎么同步呢佬，这个还没用过同步

在自己 fork 的仓库中应该有 Sync 或者 Contribute 之类的按钮，点击之后根据提示同步 openRin/Rin 的 main 分支即可

**Comment by OXeu** [comment]
![S40721-22404746_org.mozilla.firefox.png](https://github.com/user-attachments/assets/a56f6581-a782-42bb-816f-20f298fe4660)

**Comment by TIANXUAN13** [comment]
非常感谢佬，终于弄好啦

**Comment by TIANXUAN13** [comment]
想请问一下佬
<img width="417" alt="image" src="https://github.com/user-attachments/assets/e617fe86-e308-462f-87f2-a38bb5b83e20">
这个书写的这之前不是有一堆工具吗，现在是换方案了吗，那怎么设置二级标题   加粗之类的呢

**Comment by OXeu** [comment]
> 想请问一下佬
> <img width="417" alt="image" src="https://github.com/user-attachments/assets/e617fe86-e308-462f-87f2-a38bb5b83e20">
> 这个书写的这之前不是有一堆工具吗，现在是换方案了吗，那怎么设置二级标题   加粗之类的呢

换编辑器了，都支持 Markdown

**Comment by TIANXUAN13** [comment]
好的，麻烦佬了，但是现在我复制文章进去，图片默认都没有自动上传，然后得手动找位置一个一个传，这个是因为没有用markdown格式编辑的原因吗

**Comment by OXeu** [comment]
> 好的，麻烦佬了，但是现在我复制文章进去，图片默认都没有自动上传，然后得手动找位置一个一个传，这个是因为没有用markdown格式编辑的原因吗
> 

目前应该不支持粘贴时自动上传图片

**Comment by soslane** [comment]
现在创建R2桶需要绑卡了？我R2以前好像可以创建的，这次重新部署发现R2不能直接创建了

**Comment by TIANXUAN13** [comment]
> 现在创建R2桶需要绑卡了？我R2以前好像可以创建的，这次重新部署发现R2不能直接创建了

是的上次我创建就要绑卡了，不过可以用外国那种生成卡信息，再生成一个人的信息填入就可以使用啦
