### ISSUE TITLE
[Help] 希望更新本地dev教程

### ISSUE THREAD

**Issue by himesamanoyume** [openRin/Rin#226]
**描述你遇到的问题**
cf正常部署了，想在本地进行dev，跑起来了但还是有很多地方没有配置正确，能否更新一个文档教学本地搭建环境呢

**复现步骤**
1. xxxxx
2. xxx

**期望行为**
希望更新本地dev教程

**截图**

**额外信息**

**Comment by OXeu** [comment]
由于引入了动态配置，现在 S3 相关的环境变量变成了强制要求，如果之前没有配置 S3 的相关变量，可以先尝试参考部署文档相同的步骤新建一个 R2 存储桶用于本地开发

如果除此以外还遇到了其他的问题，请详细说明，同时欢迎 pr 更新文档

**Comment by himesamanoyume** [comment]
现在我希望把前端放到vercel上部署，其他的留在cf，然后前端部署完之后如果到了请求worker相关的位置就会显示404，远程地址为127.0.0.1:10809，我想知道如何改成去请求cf上的worker的地址

**Comment by himesamanoyume** [comment]
好像也可能是我部署的时候有问题？因为部署vercel的时候没能完全套用教程，就算worker出问题应该也只是首页加载不出来feeds而已

**Comment by himesamanoyume** [comment]
已解决，确实是部署的问题

**Comment by himesamanoyume** [comment]
好吧，还是不行，worker是没问题的，但是

**Comment by himesamanoyume** [comment]
我现在遇到了这么个情况，实在不知道哪里出了问题；我用了两个仓库，一个是Rin未改动过的，一个是我改动过的，分别部署在vercel和cf上，/test是我用feeds的page复制了一份改了一下得来的，worker未改动
情况|原版vercel|原版cf|改过的vercel|改过的cf|改过的本地dev
--|--|--|--|--|--
构建指令|turbo build|bun b|turbo build|bun b|bun b
输出路径|/dist|/client/dist|/dist|/client/dist|/client/dist
根目录|/client|/|/client|/|/
url|/|/|/test|/test|/test
状态|200|200|404|200|200
worker监测日志流|接收到GET请求|接收到GET请求|什么都没接收到|接收到GET请求|接收到GET请求

**Comment by OXeu** [comment]
vercel对于路径索引需要单独配置一个 config 文件的，你找一下vercel文档应该有
