### ISSUE TITLE
[Help] 问题描述rss出现错误提示Fetch API cannot load: imagerin.8072211.xyz/cache/rss.xml

### ISSUE THREAD

**Issue by maxweiwei** [openRin/Rin#228]
**描述你遇到的问题**

**复现步骤**
1. 把rss放在订阅器,提示有错误
2. 浏览器打开这个rss链接,显示Fetch API cannot load: imagerin.8072211.xyz/cache/rss.xml
3. 但是我手动访问: imagerin.8072211.xyz/cache/rss.xml,能下载到文件
可能问题比较幼稚,可是我确实搜不到有效的解决方案

**期望行为**

**截图**

**额外信息**

**Comment by PBK-B** [comment]
@maxweiwei 这个得看你使用的订阅器能否支持对 Content-Type 为 `application/octet-stream` 文件进行处理，建议使用 https://xeu.life/sub/rss.xml（`xeu.life` 部分替换为自己的域名）这会返回正确的 Content-Type

可能相关问题
https://github.com/openRin/Rin/issues/117

**Comment by maxweiwei** [comment]
> @maxweiwei 这个得看你使用的订阅器能否支持对 Content-Type 为 `application/octet-stream` 文件进行处理，建议使用 https://xeu.life/sub/rss.xml （ `xeu.life` 部分替换为自己的域名）这会返回正确的 Content-Type
> 
> 可能相关问题 #117

可能我没有表达清楚,订阅器提示订阅失败
`http://blog.8072211.xyz/sub/atom.xml (ERROR: HTTP 状态码错误 (500 Internal Server Error))`
无论是/rss还是/atmo
<img width="368" alt="Screenshot 2024-07-25 110618" src="https://github.com/user-attachments/assets/3bf79fc1-d8cb-41ba-ba36-034a1d812353">

**Comment by PBK-B** [comment]
@maxweiwei 你 S3_ACCESS_HOST 环境变量填写的是什么呀？如果是 `imagerin.8072211.xyz` 的话改成 `https://imagerin.8072211.xyz` 试试

**Comment by maxweiwei** [comment]
> @maxweiwei 你 S3_ACCESS_HOST 环境变量填写的是什么呀？如果是 `imagerin.8072211.xyz` 的话改成 `https://imagerin.8072211.xyz` 试试

我的S3_ACCESS_HOST 环境变量填写的是imagerin.8072211.xyz,改成你说的还是不行

**Comment by PBK-B** [comment]
> > @maxweiwei 你 S3_ACCESS_HOST 环境变量填写的是什么呀？如果是 `imagerin.8072211.xyz` 的话改成 `https://imagerin.8072211.xyz` 试试
> 
> 我的S3_ACCESS_HOST 环境变量填写的是imagerin.8072211.xyz,改成你说的还是不行

你有重新部署服务吗？

**Comment by maxweiwei** [comment]
> > > @maxweiwei 你 S3_ACCESS_HOST 环境变量填写的是什么呀？如果是 `imagerin.8072211.xyz` 的话改成 `https://imagerin.8072211.xyz` 试试
> > 
> > 
> > 我的S3_ACCESS_HOST 环境变量填写的是imagerin.8072211.xyz,改成你说的还是不行
> 
> 你有重新部署服务吗？
我又去试了seo部署失败了,
<img width="650" alt="image" src="https://github.com/user-attachments/assets/ab7373ba-30b6-40f3-a1cd-b4cc1ff94ad4">

**Comment by maxweiwei** [comment]
> > > > > @maxweiwei 你 S3_ACCESS_HOST 环境变量填写的是什么呀？如果是 `imagerin.8072211.xyz` 的话改成 `https://imagerin.8072211.xyz` 试试
> > > > 
> > > > 
> > > > 我的S3_ACCESS_HOST 环境变量填写的是imagerin.8072211.xyz,改成你说的还是不行
> > > 
> > > 
> > > 你有重新部署服务吗？
> > > 我又去试了seo部署失败了,
> > 
> > 
> > <img alt="image" width="650" src="https://private-user-images.githubusercontent.com/37798522/352451337-ab7373ba-30b6-40f3-a1cd-b4cc1ff94ad4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5ODI1MTAsIm5iZiI6MTcyMTk4MjIxMCwicGF0aCI6Ii8zNzc5ODUyMi8zNTI0NTEzMzctYWI3MzczYmEtMzBiNi00MGYzLWExY2QtYjRjYzFmZjk0YWQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDA4MjMzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0OTEwM2Y4NTY5ZmFjYzVkMzA5ZjU1NDZkNTA4YTkwNjZjNjBmMzYyN2NkZTEwNmNkYjA1MmZkMjAzMGFmNzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.x9FmFrZAPNmvDqA9w1pBkN5CiDx0pxI4Y2rYjvU4LRk">
> 
> SEO 最近是炸的是正常的 你应该重试 Deploy 部署

这个是成功的,又试了一下也成功了

**Comment by maxweiwei** [comment]
部署成功了,rss还是打不开

**Comment by maxweiwei** [comment]
> 部署成功了,rss还是打不开

成功了.感谢各位
