### ISSUE TITLE
[Help] 救命，无法登录

### ISSUE THREAD

**Issue by NekoMirra** [openRin/Rin#230]
按照部署文档和视频教程一步步检查了所有变量，确认没有问题

但在一切都部署完成后，尝试登录时，登录地址显示
![Clip_2024-07-30_00-30-36](https://github.com/user-attachments/assets/03e9fbb0-e970-4036-8fa6-9e01034f4be2)
Cannot read properties of undefined (reading 'redirect')
不知道怎么解决了😭

**Comment by OXeu** [comment]
暂时不清楚什么原因，你可以重新部署一下或者给后端绑定一个自定义域名再试试

**Comment by crazy0x70** [comment]
同样的问题，重新部署和绑定自定义域名仍然显示Cannot read properties of undefined (reading 'redirect')

**Comment by 534002646** [comment]
我也遇到了，更新到最新的就这样了

**Comment by OXeu** [comment]
@NekoMirra @534002646 
已修复，请更新到最新分支

**Comment by NekoMirra** [comment]
感谢！辛苦啦！

> @NekoMirra @534002646 已修复，请更新到最新分支

**Comment by NekoMirra** [comment]
![Clip_2024-09-08_11-38-13](https://github.com/user-attachments/assets/ca5be205-7a21-4382-ba34-6483b8a80a1d)
登录又出问题了。。。

**Comment by nick-cjyx9** [comment]
感觉又是那个 auth 库的问题...

**Comment by OXeu** [comment]
> ![Clip_2024-09-08_11-38-13](https://github.com/user-attachments/assets/ca5be205-7a21-4382-ba34-6483b8a80a1d)
> 登录又出问题了。。。

看看控制台打印的 state 和 p_state 是不是一样的

**Comment by NekoMirra** [comment]
> > ![Clip_2024-09-08_11-38-13](https://private-user-images.githubusercontent.com/48759390/365412586-ca5be205-7a21-4382-ba34-6483b8a80a1d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3NzczODIsIm5iZiI6MTcyNTc3NzA4MiwicGF0aCI6Ii80ODc1OTM5MC8zNjU0MTI1ODYtY2E1YmUyMDUtN2EyMS00MzgyLWJhMzQtNjQ4M2I4YTgwYTFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA4VDA2MzEyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM2NjJhMzA0Yjk2NDRjNTQ4ZjM2Nzk3N2EwMTMxZDU3NmE3M2RmOWJkYTU0NjI4NGExNWExNWEwYjFkZjdhYjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eo9jfK2Mxed0y7o9vtmAXqLYB8jWnKavHAtl1k6YlAk)
> > 登录又出问题了。。。
> 
> 看看控制台打印的 state 和 p_state 是不是一样的

确实一样，我之前还能正常登录，最近也没有动别的东西

**Comment by OXeu** [comment]
今天看了下这个问题，有可能是 Pages 的 API_URL 中末尾有斜杠 `/` 导致跳转的链接中包含`//`，设置 Cookie 失败

检查方式是在博客主页断网，点击登录检查浏览器跳转的地址

**以下跳转链接会报 state mismatch 错误**
<img width="284" alt="Image" src="https://github.com/user-attachments/assets/705962e5-ffd4-4f67-af60-a8a15479b903" />

**以下链接正常工作**
<img width="299" alt="Image" src="https://github.com/user-attachments/assets/75507002-f2ca-41f7-a2f7-b17c0b8bffe8" />

**Comment by NekoMirra** [comment]
> 今天看了下这个问题，有可能是 Pages 的 API_URL 中末尾有斜杠 `/` 导致跳转的链接中包含`//`，设置 Cookie 失败
> 
> 检查方式是在博客主页断网，点击登录检查浏览器跳转的地址
> 
> **以下跳转链接会报 state mismatch 错误** <img alt="Image" width="284" src="https://private-user-images.githubusercontent.com/36541432/404112458-705962e5-ffd4-4f67-af60-a8a15479b903.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzcxMTA4NzYsIm5iZiI6MTczNzExMDU3NiwicGF0aCI6Ii8zNjU0MTQzMi80MDQxMTI0NTgtNzA1OTYyZTUtZmZkNC00ZjY3LWFmNjAtYThhMTU0NzliOTAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTE3VDEwNDI1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmZTUzZDkxYzU4NTcxY2ZkOTFmNmRmOTE5ZTRkNzc2ODRhNWFlYmVmMDgwYWRmOTNkMzc2NGRjNjhhYzM3ZTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9kBqNG8Ae2pnQgxAa4TXPnXQUemaNKrPInfY-UJX36Q">
> 
> **以下链接正常工作** <img alt="Image" width="299" src="https://private-user-images.githubusercontent.com/36541432/404112740-75507002-f2ca-41f7-a2f7-b17c0b8bffe8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzcxMTA4NzYsIm5iZiI6MTczNzExMDU3NiwicGF0aCI6Ii8zNjU0MTQzMi80MDQxMTI3NDAtNzU1MDcwMDItZjJjYS00MWY3LWEyZjctYjE3YzBiOGJmZmU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTE3VDEwNDI1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiNTA4ZTY1MWU3ZGVmNWYyNDhjZTllY2FiZmVmZWJkMGI5OTJjZGMzNjA3ZmZlNGMzZTI4ZThjMTVlNGRhMDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.o7l88z_g0cS4Jk-SiW8wtCKC5U_ZrpHNwfKXYwpQs2c">

感谢回复！我再次进行检查~

**Comment by NekoMirra** [comment]
> 今天看了下这个问题，有可能是 Pages 的 API_URL 中末尾有斜杠 `/` 导致跳转的链接中包含`//`，设置 Cookie 失败
> 
> 检查方式是在博客主页断网，点击登录检查浏览器跳转的地址
> 
> **以下跳转链接会报 state mismatch 错误** <img alt="Image" width="284" src="https://private-user-images.githubusercontent.com/36541432/404112458-705962e5-ffd4-4f67-af60-a8a15479b903.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzcxMTA5MzMsIm5iZiI6MTczNzExMDYzMywicGF0aCI6Ii8zNjU0MTQzMi80MDQxMTI0NTgtNzA1OTYyZTUtZmZkNC00ZjY3LWFmNjAtYThhMTU0NzliOTAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTE3VDEwNDM1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhYTMyNDZjOTUxMzgxNTIxNzY1ZmQ4NTc5MjA5ZjVlNjQ3MmM0ZDk5NjI4ZTNkYmE0YTQxMWMzODk1NGU3MzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wV527YhB7SGyX6JPzTuNWiFbcOmeE72LT1R9Z0i1kUE">
> 
> **以下链接正常工作** <img alt="Image" width="299" src="https://private-user-images.githubusercontent.com/36541432/404112740-75507002-f2ca-41f7-a2f7-b17c0b8bffe8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzcxMTA5MzMsIm5iZiI6MTczNzExMDYzMywicGF0aCI6Ii8zNjU0MTQzMi80MDQxMTI3NDAtNzU1MDcwMDItZjJjYS00MWY3LWEyZjctYjE3YzBiOGJmZmU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTE3VDEwNDM1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhNTVkMjk1NzM2N2FhMjRhMmVlMWIzZTM3ZDJjNTI3ZDg1YzIzZDU4NDY0ODA2N2ExY2NmYzA4NjY5ZTJiMDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NDe1f70YM1DD8eyq7bsI9XFwAuKqPUSpgvc8f2VjyRY">

断网检查了，但是链接无误，我找机会重新部署吧
