### ISSUE TITLE
同步了你的仓库后部署失败了

### ISSUE THREAD

**Issue by soslane** [openRin/Rin#236]
**描述你遇到的问题**
同步了你的仓库后部署失败了
**复现步骤**

**期望行为**
如何修复

**截图**
![image](https://github.com/user-attachments/assets/70103753-b718-4a5e-87d7-1b05d602b69f)

**额外信息**

**Comment by PBK-B** [comment]
@soslane Cloudflare API 配置信息填写对了吗？[可以参考文档](https://rin-docs.xeu.life/guide/deploy.html#%E8%8E%B7%E5%8F%96%E7%94%A8%E6%88%B7-id-%E4%B8%8E-api-%E4%BB%A4%E7%89%8C)

**Comment by soslane** [comment]
Api我跟着操作视频做的，设置了失效时间。。。。后来我重新生成了api就可以了，没再设置失效时间就可以了发自我的 iPhone在 2024年8月6日，21:45，PBK Bin ***@***.***> 写道：﻿
@soslane Cloudflare API 配置信息填写对了吗？可以参考文档
