### ISSUE TITLE
[Help] 问题描述

### ISSUE THREAD

**Issue by ghost** [openRin/Rin#241]
**描述你遇到的问题**
数据无法保存
**复现步骤**
1. xxxxx
2. xxx

**期望行为**
把讨人厌的github登录删了改为账号密码哪怕微信登录

**截图**

**额外信息**

**Comment by nick-cjyx9** [comment]
删了谁对其他使用 Github Oauth 的用户负责？开 issue 前请动动脑子。

duplicated #146
