### ISSUE TITLE
[Help] 上传照片失败

### ISSUE THREAD

**Issue by OriyukiAkari** [openRin/Rin#247]
**描述你遇到的问题**

**复现步骤**
1. xxxxx
2. xxx

**期望行为**

**截图**
![image](https://github.com/user-attachments/assets/5e6563f1-3add-4072-afa3-7b8d8a0e9aeb)

**额外信息**
上传图片一直在转圈，查看Issues有但是不相同，F12查看结果是Unauthorized，不知道哪里出错了，重新部署了也一样

**Comment by pugaizai** [comment]
我猜是R2桶的令牌权限或者相关变量没配好

**Comment by OriyukiAkari** [comment]
> 我猜是R2桶的令牌权限或者相关变量没配好

我又全部推倒按照部署教程重新过了一遍，结果还是如此，好奇怪

**Comment by pugaizai** [comment]
你可以到R2桶里面看看有没有cache文件夹

**Comment by OriyukiAkari** [comment]
> 你可以到R2桶里面看看有没有cache文件夹

好像是空的
![image](https://github.com/user-attachments/assets/4a67ff90-e169-48d3-b088-723f35eeb466)

**Comment by pugaizai** [comment]
那就是没配好，自己再检查下吧，记得github variable变量那里所有的URL链接后面都没 /

**Comment by OriyukiAkari** [comment]
> 那就是没配好，自己再检查下吧，记得github variable变量那里所有的URL链接后面都没 / 还有API 令牌有两个，一个是R2的一个是账户的

谢谢，排除了variable变量的S3的链接的一根/，但是问题依旧，我很好奇R2的令牌有啥用，复制下来了没用上......

**Comment by pugaizai** [comment]
> > 那就是没配好，自己再检查下吧，记得github variable变量那里所有的URL链接后面都没 / 还有API 令牌有两个，一个是R2的一个是账户的
> 
> 谢谢，排除了variable变量的S3的链接的一根/，但是问题依旧，我很好奇R2的令牌有啥用，复制下来了没用上......

说明你文档看漏了
S3_ACCESS_KEY_ID=<你的S3AccessKeyID>
S3_SECRET_ACCESS_KEY=<你的S3SecretAccessKey>
这两个要设置的，再去看看文档吧

**Comment by OriyukiAkari** [comment]
> > > 那就是没配好，自己再检查下吧，记得github variable变量那里所有的URL链接后面都没 / 还有API 令牌有两个，一个是R2的一个是账户的
> > 
> > 
> > 谢谢，排除了variable变量的S3的链接的一根/，但是问题依旧，我很好奇R2的令牌有啥用，复制下来了没用上......
> 
> 说明你文档看漏了 S3_ACCESS_KEY_ID=<你的S3AccessKeyID> S3_SECRET_ACCESS_KEY=<你的S3SecretAccessKey> 这两个要设置的，再去看看文档吧，弄好了记得重新部署

我确实没明白，重新读了一遍，看出来需要Cloudflare的账户ID，Cloudflare的用户API令牌值，Github Client ID， Github Client Secret，一个随机密码，存储桶API访问密钥和机密访问密钥这些，没明白究竟错在哪，望赐教。

**Comment by pugaizai** [comment]
github workflow那里重新deploy了吗

**Comment by OriyukiAkari** [comment]
> github workflow那里重新deploy了吗

两边都重新运行了，还是这样......我真的会谢

**Comment by pugaizai** [comment]
> > github workflow那里重新deploy了吗
> 
> 两边都重新运行了，还是这样......我真的会谢

S3_ACCESS_KEY_ID=<你的S3AccessKeyID>
S3_SECRET_ACCESS_KEY=<你的S3SecretAccessKey>

我觉得还是因为你这两个没配好的原因，尝试重新生成一个R2桶的API令牌吧，看看文档里的视频对照着有没有疏漏

> 我确实没明白，重新读了一遍，看出来需要Cloudflare的账户ID，Cloudflare的用户API令牌值，Github Client ID， Github Client Secret，一个随机密码，存储桶API访问密钥和机密访问密钥这些，没明白究竟错在哪，望赐教。

存储桶API访问密钥` 应该为存储桶API密钥ID？

**Comment by OriyukiAkari** [comment]
> > > github workflow那里重新deploy了吗
> > 
> > 
> > 两边都重新运行了，还是这样......我真的会谢
> 
> S3_ACCESS_KEY_ID=<你的S3AccessKeyID> S3_SECRET_ACCESS_KEY=<你的S3SecretAccessKey>
> 
> 我觉得还是因为你这两个没配好的原因，尝试重新生成一个R2桶的API令牌吧，看看文档里的视频对照着有没有疏漏
> 
> > 我确实没明白，重新读了一遍，看出来需要Cloudflare的账户ID，Cloudflare的用户API令牌值，Github Client ID， Github Client Secret，一个随机密码，存储桶API访问密钥和机密访问密钥这些，没明白究竟错在哪，望赐教。
> 
> `存储桶API访问密钥` 应该为存储桶API密钥ID？

我再看看...R2生成的有三个，API，密钥和机器密钥，我目前填的是后两者

**Comment by OriyukiAkari** [comment]
> > > github workflow那里重新deploy了吗
> > 
> > 
> > 两边都重新运行了，还是这样......我真的会谢
> 
> S3_ACCESS_KEY_ID=<你的S3AccessKeyID> S3_SECRET_ACCESS_KEY=<你的S3SecretAccessKey>
> 
> 我觉得还是因为你这两个没配好的原因，尝试重新生成一个R2桶的API令牌吧，看看文档里的视频对照着有没有疏漏
> 
> > 我确实没明白，重新读了一遍，看出来需要Cloudflare的账户ID，Cloudflare的用户API令牌值，Github Client ID， Github Client Secret，一个随机密码，存储桶API访问密钥和机密访问密钥这些，没明白究竟错在哪，望赐教。
> 
> `存储桶API访问密钥` 应该为存储桶API密钥ID？

因为第三方文档也是采用这两个
![image](https://github.com/user-attachments/assets/76790431-4540-4649-a47e-a611fec64ad3)

**Comment by pugaizai** [comment]
确实是这两个

**Comment by OriyukiAkari** [comment]
> 确实是这两个

但是输入这俩就是不对😢

**Comment by pugaizai** [comment]
看看你的
S3_ACCESS_HOST和S3_ENDPOINT

**Comment by OriyukiAkari** [comment]
> 看看你的 S3_ACCESS_HOST和S3_ENDPOINT

这俩一个是S3的绑定域名，一个是S3的API，我确定都没问题

**Comment by pugaizai** [comment]
S3_ENDPOINT 应该是类似 https://<账户ID>.r2.cloudflarestorage.com 的，后面并没有带R2桶名。

https://<账户ID>.r2.cloudflarestorage.com/<R2桶名> ，如果是这样就错了

**Comment by OriyukiAkari** [comment]
是前者，

> S3_ENDPOINT 应该是类似 https://<账户ID>.r2.cloudflarestorage.com 的，后面并没有带R2桶名。
> 
> https://<账户ID>.r2.cloudflarestorage.com/<R2桶名> ，如果是这样就错了

是前者，第一次排除时去掉了最后面的 /，结果忙活到现在前后端直接分离连不上了......明天早上再看看怎么解决吧

**Comment by OXeu** [comment]
会不会是 S3_ACCESS_KEY_ID 和 S3_SECRET_ACCESS_KEY 填反了？
S3_ACCESS_KEY_ID 填的是`访问密钥ID`，是短的那个
S3_SECRET_ACCESS_KEY 填的是`机密访问密钥`，长的那个
另外检查下填进去的是不是不小心多带了空格换行之类的多余内容

**Comment by OriyukiAkari** [comment]
> 会不会是 S3_ACCESS_KEY_ID 和 S3_SECRET_ACCESS_KEY 填反了？ S3_ACCESS_KEY_ID 填的是`访问密钥ID`，是短的那个 S3_SECRET_ACCESS_KEY 填的是`机密访问密钥`，长的那个 另外检查下填进去的是不是不小心多带了空格换行之类的多余内容

我确定是先短的后长的
早上又重新推倒重来了，这次在Github上填东西的时候直接手敲的，最后F12结果还是未授权......

**Comment by OriyukiAkari** [comment]
> > 会不会是 S3_ACCESS_KEY_ID 和 S3_SECRET_ACCESS_KEY 填反了？ S3_ACCESS_KEY_ID 填的是`访问密钥ID`，是短的那个 S3_SECRET_ACCESS_KEY 填的是`机密访问密钥`，长的那个 另外检查下填进去的是不是不小心多带了空格换行之类的多余内容
> 
> 我确定是先短的后长的 早上又重新推倒重来了，这次在Github上填东西的时候直接手敲的，最后F12结果还是未授权......


> 会不会是 S3_ACCESS_KEY_ID 和 S3_SECRET_ACCESS_KEY 填反了？ S3_ACCESS_KEY_ID 填的是`访问密钥ID`，是短的那个 S3_SECRET_ACCESS_KEY 填的是`机密访问密钥`，长的那个 另外检查下填进去的是不是不小心多带了空格换行之类的多余内容

另外重新部署之后，Worker似乎炸了：“workers.api.error.deployment_not_found (Code: 100146)”，感觉压根就没工作

**Comment by OriyukiAkari** [comment]
> S3_ENDPOINT 应该是类似 https://<账户ID>.r2.cloudflarestorage.com 的，后面并没有带R2桶名。
> 
> https://<账户ID>.r2.cloudflarestorage.com/<R2桶名> ，如果是这样就错了

解决了，断断续续试了四五次，最后一次发现账户API和R2 API显示在一起的，前面的七八次都没看见，总之在迷迷糊糊中解决了

**Comment by iuiurun** [comment]
S3_ACCESS_KEY_ID=<你的S3AccessKeyID>
S3_SECRET_ACCESS_KEY=<你的S3SecretAccessKey>
这两个在哪里获取的？我看视频里面也没有
