### ISSUE TITLE
[Help] RSS生成失败

### ISSUE THREAD

**Issue by pugaizai** [openRin/Rin#248]
**描述你遇到的问题**
已按照文档配置了 workers 路由 

访问 https://域名/sub/rss.xml 提示404 ，在r2桶里面也没找到生成的rss订阅

**Comment by pugaizai** [comment]
新建文章上传图片什么的都没问题

**Comment by pugaizai** [comment]
看了下别人的博客，也是没法用RSS，暂且先把ISSUE重新打开了

**Comment by astych666** [comment]
我的问题和你一样，我起初以为是因为我自建的s3的问题，但是images和cache文件夹正常存在的，图片可以正常上传，所以应该不是我的问题。翻看issue找到了这个[issue](https://github.com/openRin/Rin/issues/158)里提到rss依赖于crontab，但目前cf后端cron事件一直在报错，在cf上抓了log也看不出个所以然，下面是报错log，盲猜是开发者还没有修这个bug，但是我看开发者自己的blog rss就是正常的就很奇怪。
```
{
  "truncated": false,
  "outcome": "exception",
  "scriptVersion": {
    "id": "****"
  },
  "scriptName": "rin-server",
  "diagnosticsChannelEvents": [],
  "exceptions": [
    {
      "stack": "ServiceNotFoundError\n    at new ServiceNotFoundError2 (_worker.js:57015:26)\n    at ContainerInstance2.get (_worker.js:57143:13)\n    at Container2.get (_worker.js:57362:34)\n    at ServerConfig (_worker.js:69512:39)\n    at friendCrontab (_worker.js:70329:19)\n    at Object.scheduled (_worker.js:87388:11)",
      "name": "Error",
      "message": "",
      "timestamp": 1725276059453
    }
  ],
  "logs": [],
  "eventTimestamp": 1725276059340,
  "event": {
    "cron": "*/20 * * * *",
    "scheduledTime": 1725276059000
  },
  "id": 0
}
```

**Comment by pugaizai** [comment]
> 我的问题和你一样，我起初以为是因为我自建的s3的问题，但是images和cache文件夹正常存在的，图片可以正常上传，所以应该不是我的问题。翻看issue找到了这个[issue](https://github.com/openRin/Rin/issues/158#issuecomment-2198176296)里提到rss依赖于crontab，但目前cf后端cron事件一直在报错，在cf上抓了log也看不出个所以然，下面是报错log，盲猜是开发者还没有修这个bug，但是我看开发者自己的blog rss就是正常的就很奇怪。
> 
> ```
> {
>   "truncated": false,
>   "outcome": "exception",
>   "scriptVersion": {
>     "id": "****"
>   },
>   "scriptName": "rin-server",
>   "diagnosticsChannelEvents": [],
>   "exceptions": [
>     {
>       "stack": "ServiceNotFoundError\n    at new ServiceNotFoundError2 (_worker.js:57015:26)\n    at ContainerInstance2.get (_worker.js:57143:13)\n    at Container2.get (_worker.js:57362:34)\n    at ServerConfig (_worker.js:69512:39)\n    at friendCrontab (_worker.js:70329:19)\n    at Object.scheduled (_worker.js:87388:11)",
>       "name": "Error",
>       "message": "",
>       "timestamp": 1725276059453
>     }
>   ],
>   "logs": [],
>   "eventTimestamp": 1725276059340,
>   "event": {
>     "cron": "*/20 * * * *",
>     "scheduledTime": 1725276059000
>   },
>   "id": 0
> }
> ```

还以为是我自己的问题呢，我寻思怎么没人开issue

**Comment by qiqi1qiqi** [comment]
访问 [https://域名/sub/rss.xml](https://xn--eqrt2g/sub/rss.xml) 提示404
<html>
<head><title>400 Bad Request</title></head>
<body>
<center><h1>400 Bad Request</h1></center>
<hr><center>cloudflare</center>
</body>
</html>
