### ISSUE TITLE
[Help] 貌似刷到了一个Bug，写了一行代码写作页面崩溃了

### ISSUE THREAD

**Issue by OriyukiAkari** [openRin/Rin#249]
**描述你遇到的问题**
写作页面白屏，F12提示：InvalidCharacterError: Failed to execute 'createElement' on 'Document': The tag name provided ('svgclass="octicon"') is not a valid name.

光标在文段行没有中文时候会漂移

**复现步骤**
忘了，好像是用CSS写东西的时候

**期望行为**

**截图**
![image](https://github.com/user-attachments/assets/118620b0-341c-44e0-8576-37cb1ad014cf)

**额外信息**
至此，写作页面废了，已经创建的文章可以继续修改上传写作，但是无法创建新的文章

**Comment by OriyukiAkari** [comment]
清理了R2缓存，重新部署无效
最后有点无奈换了Macbook登录竟然可以了，回到Windows换了浏览器也可以了，唯独edge不行，这下是浏览器的问题了
清理了edge的缓存还是不行，换了一个用户配置也好了，但是我很好奇这个错误的影响因素就行是什么

**Comment by OXeu** [comment]
估计是 Edge 插件的问题，可以把插件全禁用了试试

**Comment by OriyukiAkari** [comment]
> 估计是 Edge 插件的问题，可以把插件全禁用了试试

![屏幕截图 2024-09-05 160656](https://github.com/user-attachments/assets/c58db5fc-dbb7-4c51-9058-13e195c1dfed)

貌似不是......关完了还是这样，已对edge失望，占用高效能差，后续迁移到Chrome之后再试试清除cookle之类的尝试一下，总之感谢你

**Comment by OXeu** [comment]
> > 估计是 Edge 插件的问题，可以把插件全禁用了试试
> 
> ![屏幕截图 2024-09-05 160656](https://github.com/user-attachments/assets/c58db5fc-dbb7-4c51-9058-13e195c1dfed)
> 
> 貌似不是......关完了还是这样，已对edge失望，占用高效能差，后续迁移到Chrome之后再试试清除cookle之类的尝试一下，总之感谢你

edge开隐私标签页试试呢

**Comment by OriyukiAkari** [comment]
> edge开隐私标签页试试呢

早上耐不住chrome不习惯，索性直接删了用户配置重新建就好了，我猜这个应该是写入了用户配置里，但是又不知道谁是哪里

**Comment by OXeu** [comment]
重新看了下问题，如果是因为固定的内容导致渲染失败白屏的话，那确实是会这样，浏览器本地有使用 localstorage 保存草稿，下次重进会恢复上次的编辑内容，需要 F12 打开应用程序选项卡，在本地存储处手动删除保存的草稿内容

**Comment by OriyukiAkari** [comment]
好耶，果然是大佬，问题结束（）
