### ISSUE TITLE
写作操作问题

### ISSUE THREAD

**Issue by zhongziso** [openRin/Rin#252]
大佬，搭建文章里面的绿色，红色，蓝色这些怎么写的 还有就是写作的时候怎么指标显示的位置是错位的，换了游览器也是一样

**Comment by OriyukiAkari** [comment]
html+css代码实现，不会写的话建议用F12直接韩国了（?

**Comment by OXeu** [comment]
用的是 GitHub Flavor Markdown 的警告扩展
```
> [!note]
> 注释文字

> [!important]
> 重要文字

> [!tip]
> 提示文字

> [!warning]
> 注意文字

> [!caution]
> 警告文字
```

**效果**

> [!note]
> 注释文字

> [!important]
> 重要文字

> [!tip]
> 提示文字

> [!warning]
> 注意文字

> [!caution]
> 警告文字

**Comment by zhongziso** [comment]
谢谢大佬百忙抽空回复，我研究看看，代码类的东西不太懂，都是引用网上的

**Comment by zhongziso** [comment]
<h2 id="part1">第一部分</h2>


<h2 id="part2">第二部分</h2>


<h2 id="part3">第三部分</h2>
上面这样写目录是成功的
<h2 id="part3-1">第三部分的第一小部分</h2>
大目录下的小目录这样填写失败了，请问目录下的目录怎么写呢，谢谢

**Comment by OXeu** [comment]
> ```
> <h2 id="part1">第一部分</h2>
> 
> 
> <h2 id="part2">第二部分</h2>
> 
> 
> <h2 id="part3">第三部分</h2>
> 上面这样写目录是成功的
> <h2 id="part3-1">第三部分的第一小部分</h2>
> 大目录下的小目录这样填写失败了，请问目录下的目录怎么写呢，谢谢

直接用 Markdown 就好了
html 的话对应的是 h1,h2,h3

**Comment by zhongziso** [comment]
> > ```
> > <h2 id="part1">第一部分</h2>
> > 
> > 
> > <h2 id="part2">第二部分</h2>
> > 
> > 
> > <h2 id="part3">第三部分</h2>
> > 上面这样写目录是成功的
> > <h2 id="part3-1">第三部分的第一小部分</h2>
> > 大目录下的小目录这样填写失败了，请问目录下的目录怎么写呢，谢谢
> > ```
> 
> 直接用 Markdown 就可以
> 
> ```
> # 第一部分
> 
> # 第二部分
> 
> # 第三部分
> 
> ## 第三部分的第一小部分
> ```
> 
> html 的话是对应 h1,h2,h3

完美，谢谢大佬的回复，谢谢！

**Comment by Red22ss** [comment]
[!note] 
这样么？
 [!note]
