### ISSUE TITLE
[Feature Request] 文章直接渲染HTML

### ISSUE THREAD

**Issue by SkrShadow** [openRin/Rin#255]
**您的功能请求是否与问题相关？请描述**
目前的状态如链接所示
https://blog.sumika.icu/feed/1
下方的“Q/A”部分算号器是使用HTML实现的，但是现在会直接显示出原文

**描述您想要的解决方案**
希望可以直接渲染HTML部分

（非专业可能有点表述不清，作者大大点进我的主页应该就知道我在说什么了，提前谢谢大大QuQ）

**Comment by OXeu** [comment]
现在是支持直接插入 html 节点的，直接插入 <script> 标签就可以了，也不需要要写 `{% raw %}` 之类的标签，同时不要在外层包裹 body 和 html 等内容，反而会解析不了
![图片](https://github.com/user-attachments/assets/1273fb81-253f-4a6e-8900-48840f248663)

**Comment by SkrShadow** [comment]
谢谢大佬，已经改好啦
