### ISSUE TITLE
“关于”  这个问题 不出页面  博主怎么解决？

### ISSUE THREAD

**Issue by fofieblog** [openRin/Rin#261]
按照提示 设置了 别名设置为 about 

还出现 ，

Not found TIPS  将文章别名设置为 about 可以创建关于页面

**Comment by fofieblog** [comment]
谢谢博主， 我就是 在标题上 命名其他文字了， 原来要填写关于  完美解决了，

**Comment by OXeu** [comment]
> 谢谢博主， 我就是 在标题上 命名其他文字了， 原来要填写关于  完美解决了，

标题没有关系吧，我看了下你之前是别名末尾多了一个空格
