### ISSUE TITLE
[Help] 前端页面正常，但是登录的时候会显示404 not found

### ISSUE THREAD

**Issue by LILAIAJG** [openRin/Rin#264]
![404](https://github.com/user-attachments/assets/1b9df668-ac1a-428a-9ba1-bdbd3cb16732)
部署完以后进入前端页面登录时就会出现

**Comment by OXeu** [comment]
这是把 API_URL 填成 R2 的地址了？

**Comment by LILAIAJG** [comment]
> 这是把 API_URL 填成 R2 的地址了？

 不好意思，应该填什么啊

**Comment by OXeu** [comment]
> > 这是把 API_URL 填成 R2 的地址了？
> 
>  不好意思，应该填什么啊

你的 worker 的地址

**Comment by LILAIAJG** [comment]
> > > 这是把 API_URL 填成 R2 的地址了？
> > 
> > 
> > 不好意思，应该填什么啊
> 
> 你的 worker 的地址

![work](https://github.com/user-attachments/assets/9e678e36-bc14-43e6-b357-2b1ac16c5c07)
是这个吗？
