### ISSUE TITLE
[Help] 问题描述

### ISSUE THREAD

**Issue by RTAkland** [openRin/Rin#277]
**描述你遇到的问题**
rss订阅显示404: No such page!， 但是r2里面生成了.xml和.json rss文件，
s3 public url末尾没有`/`

**复现步骤**

**期望行为**

**截图**

**额外信息**

**Comment by OXeu** [comment]
参见 Workers 路由一节，还需要配置路由

http://rin-docs.xeu.life/guide/rss.html#workers-路由
