### ISSUE TITLE
[Bug] 文章有概率会消失

### ISSUE THREAD

**Issue by RTAkland** [openRin/Rin#278]
**Bug 描述**
在发布一篇文章后大概十几分钟之后文章会在`文章标签`内消失,但是在`时间轴`中却有

**截图**
![46e96ca409d1c2f5f6e4e27c7965a13f](https://github.com/user-attachments/assets/10614828-b2ce-4c37-8408-1307e1f4fc2f)
![3061ebfb7fa7f3c5ba75ecd3e750b65f](https://github.com/user-attachments/assets/ec3d1f7d-fee5-438b-913f-f62a9473f056)

**Comment by PBK-B** [comment]
@RTAkland 私有文章好像不会显示？我刚刚看了一下你站点这三篇文章好像在标签里有的呀

**Comment by RTAkland** [comment]
> @RTAkland 私有文章好像不会显示？我刚刚看了一下你站点这三篇文章好像在标签里有的呀

emmm但是我的文章不是私有的

**Comment by RTAkland** [comment]
另外我的意思是`文章标签`指的是`文章`这个标签我分词分错了不好意思

**Comment by OXeu** [comment]
可能是缓存没更新的问题，在博客的设置页面清除一下缓存试试

**Comment by RTAkland** [comment]
> 可能是缓存没更新的问题，在博客的设置页面清除一下缓存试试

解决了感谢

**Comment by 9thChasingWindGirl** [comment]
#327
