### ISSUE TITLE
[Help] 我们发布文章的时候想要设置一些格式要怎么设置？

### ISSUE THREAD

**Issue by ZLY3439569179** [openRin/Rin#280]
**在我们发布文章的时候想要设置各级标题，文字加粗、居中对齐等格式的时候，要怎么编写才能实现出发布的文章有想要的效果？**
![无标题](https://github.com/user-attachments/assets/4a01fb71-3574-4e5a-bce4-060d9cf7d8e0)
**编写的时候没有设置一些常用格式的按钮。（个人观点 有点太简洁，对于一些小白玩家不太友好）**

**Comment by OXeu** [comment]
编辑器支持 Github 风格的 Markdown 格式，具体参见
https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax
