### ISSUE TITLE
为啥手机端内容加载不出来？电脑上可以显示

### ISSUE THREAD

**Issue by ligege2000** [openRin/Rin#282]
登录也打不开不能跳转Github

**Comment by PBK-B** [comment]
@ligege2000 有截图吗？或者可以补充一下环境信息比如 `android` 上 `chrome` 浏览器打不开的页面是 `demo.com/about`

**Comment by ligege2000** [comment]
![Screenshot_20241106_122807_com.huawei.browser_edit_102897294146798.jpg](https://github.com/user-attachments/assets/3f7cac76-e8be-42c5-b3c4-4e62079f1ed4)

手机端这里的内容一直加载不出来，登录不跳转GitHub，电脑上浏览正常的。> @ligege2000 有截图吗？或者可以补充一下环境信息比如 `android` 上 `chrome` 浏览器打不开的页面是 `demo.com/about`
