### ISSUE TITLE
[Help] 能否重新设置管理员

### ISSUE THREAD

**Issue by gcasini13** [openRin/Rin#285]
**能否重新设置管理员，因为github 选择登录，选错账号了**

**Comment by OXeu** [comment]
在 Cloudflare Dashboard 中选择 D1 SQL 数据库，选择对应的数据库中的 users 表，将你需要设为管理员的账号项中的 permission 设置为 1 即可，如果需要取消设置某个管理员权限的账号，将其 permission 字段留空即可
