### ISSUE TITLE
[Feature Request] 能否添加回复评论邮件通知

### ISSUE THREAD

**Issue by RTAkland** [openRin/Rin#287]
**您的功能请求是否与问题相关？请描述**
有关

**描述您想要的解决方案**
一个可选的配置，配置一个smtp服务器用于发件，在用户回复了文章之后使用邮件通知管理员

**Comment by OXeu** [comment]
目前暂无相关计划，
不过可参考这篇文章配置充当临时解决方案

https://blog.kafuchino.top/feed/1
