### ISSUE TITLE
[Help] 请问部署教程中的“加密环境变量”怎么操作？

### ISSUE THREAD

**Issue by raikiriww** [openRin/Rin#297]
**描述你遇到的问题**
部署章节：https://docs.openrin.org/guide/deploy.html#%E5%88%9B%E5%BB%BA-r2-%E6%A1%B6 的最后有一个 tip:

> TIP
在所有环境变量调试完毕后可点击加密按钮加密环境变量（只保留 FRONTEND_URL 和 S3_FOLDER），这样下次部署时加密的环境变量就不会覆盖/删除了

但是在 github 的 Actions secrets and variables 的 Variables 中并没有找到加密按钮，这个加密按钮在哪？

**Comment by OXeu** [comment]
这个是在 Cloudflare Dashboard 手动填写环境变量调试时的操作（每次修改环境变量后无需重新部署），所有变量都通过 GitHub Action 部署直接忽略即可

**Comment by raikiriww** [comment]
好的，谢谢。
