### ISSUE TITLE
[Help] 后端503了

### ISSUE THREAD

**Issue by RTAkland** [openRin/Rin#302]
**描述你遇到的问题**

下午想打开网站发现加载特别慢然后刷新好几次才能显示出内容，刚才又试了一下已经完全显示不出来内容了，然后我尝试了一下手动触发workflow重新部署，还是503我又打开了日志发现是超过了cpu执行时间，json如下所示
```json
{
  "message": "Worker exceeded CPU time limit.",
  "exception": {
    "name": "Error",
    "message": "Worker exceeded CPU time limit.",
    "timestamp": 1735643630426
  },
  "$cloudflare": {
    "event": {
      "request": {
        "url": "https://rin-server.markushammered.workers.dev/",
        "method": "GET",
        "path": "/"
      }
    },
    "scriptName": "rin-server",
    "eventType": "fetch",
    "executionModel": "stateless",
    "scriptVersion": {
      "id": "96d35ff9-26ab-429e-be0a-db5c0f8a54c4"
    },
    "truncated": false,
    "$metadata": {
      "requestId": "8fa9d7b1ed3cfd4a"
    }
  }
}
```

**复现步骤**
打开https://rin-server.markushammered.workers.dev/

**截图**

**额外信息**

**Comment by RTAkland** [comment]
我的博客就十几篇内容也没有人看就我一个人在用

**Comment by RTAkland** [comment]
我现在正在尝试把worker删掉重新部署

**Comment by OXeu** [comment]
已知问题 https://github.com/openRin/Rin/pull/288#issuecomment-2511113223

尝试同步最新  main 分支或 dev 分支

**Comment by RTAkland** [comment]
好谢谢~

**Comment by OXeu** [comment]
刚尝试发现 Cloudflare 的 Smart Placement 也会导致这个问题，尝试设置为默认后恢复正常
![图片](https://github.com/user-attachments/assets/72b89aca-1f30-4acf-8436-d058a245b5ba)
